# Generated by Django 3.1.7 on 2021-04-06 11:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210405_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='نام شرکت')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تلفن')),
                ('description', models.TextField(max_length=512, verbose_name='توضیحات')),
                ('address', models.CharField(max_length=256, verbose_name='آدرس')),
                ('email', models.EmailField(max_length=256, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='آدرس مقاله'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='آدرس دسته بندی'),
        ),
    ]
