# Generated by Django 3.1.7 on 2021-04-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210406_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=128, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='محتوا'),
        ),
    ]
