# Generated by Django 3.1.7 on 2021-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210407_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='', null=True, upload_to='images', verbose_name='تصویر مقاله'),
        ),
    ]
