# Generated by Django 3.1.7 on 2021-04-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210407_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images', verbose_name='تصویر مقاله'),
            preserve_default=False,
        ),
    ]
